config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'all_users' => 'epicenter#all_users'

  get 'all_followers' => 'epicenter#all_followers'

  get 'all_following' => 'epicenter#all_following'

  get 'epicenter/jquery_practice' 

  get 'tag_index' => 'epicenter#tag_index'

  resources :tweets
  devise_for :users

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	 validates :message, presence: true
  validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/tweet_tag.rb
class TweetTag < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets

   validates :username, presence: true
  validates :username, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following, :avatar) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following, :avatar) }

  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_filter :authenticate_user!

  def feed

    @tweet = Tweet.new

  	@following_tweets = []

  	@tweets = Tweet.order(created_at: :desc)

  	@tweets.each do |t|
  		if current_user.following.include?(t.user_id) || current_user.id == t.user_id
  		@following_tweets.push(t)
  		end
  	end

    @follower_count = 0
    @users = User.all
    @users.each do |user|
      if user.following.include?(current_user.id)
        follower_count += 1
      end
    end

  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	user = User.find(params[:id])
  	current_user.following.push(user.id)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def unfollow
  	user = User.find(params[:id])
  	current_user.following.delete(user.id)
  	current_user.save

  	redirect_to show_user_path(id: params[:id])
  end

  def all_users
    @users = User.all
  end

  def tag_index
    @tags = Tag.all
  end

  def all_followers
    @users = []
    User.all.each do |user|
      if user.following.include?(current_user.id)
        @users.push(user)
      end
    end 
  end

  def all_following
    @users = []
    current_user.following.each do |x|
      user = User.find(x)
      @users.push(user)
    end
  end 


  def jquery_practice 
  end 

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # before_filter :authenticate_user!

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        tweet_array = @tweet.message.split(" ")

        tag_array = Tag.pluck(:tag_content)

        if tweet_array.last.start_with?("#")
          if tag_array.include?(tweet_array.last)
            tweet_tag = TweetTag.new
            tweet_tag.tweet_id = @tweet.id
            tag = Tag.find_by(tag_content: tweet_array.last)
            tweet_tag.tag_id = tag.id
            tweet_tag.save
          else
            tag = Tag.new
            tag.tag_content = tweet_array.last
            tag.save 
            tweet_tag = TweetTag.new
            tweet_tag.tweet_id = @tweet.id
            tweet_tag.tag_id = tag.id
            tweet_tag.save
          end

        end

      

        format.html { redirect_to @root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    tweet_tag = TweetTag.find_by(tweet_id: @tweet.id)
    if tweet_tag != nil
      tweet_tag.destroy
    end

    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/_userloop.html.erb
<div class="row">
	<% @users.each do |user| %>
		<% if user.id != current_user.id %>

			<div class="col-md-4">
				<%= link_to show_user_path(id: user.id) do %>
				<div class="well">
					<p><%= image_tag user.avatar.url(:medium) %></p>
					<p>@<%= user.username %></p>
					<p><%= user.name %></p>
					<p><%= user.location %></p>
				</div>
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/epicenter/all_followers.html.erb
<%= render 'userloop' %>

app/views/epicenter/all_following.html.erb
<%= render 'userloop' %>

app/views/epicenter/all_users.html.erb
<div class="row">
	<% @users.each do |user| %>
		<% if user.id != current_user.id %>

			<div class="col-md-4">
				<%= link_to show_user_path(id: user.id) do %>
				<div class="well">
					<p><%= image_tag user.avatar.url(:medium) %></p>
					<p>@<%= user.username %></p>
					<p><%= user.name %></p>
					<p><%= user.location %></p>
				</div>
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/epicenter/feed.html.erb
<div class="row">

	<div class="col-md-4">
		<div class="well">
			<h1><%= current_user.username %>'s Profile &amp Tweets</h1>
			<p><%= image_tag @current_user.avatar.url(:medium) %></p>
			<p><%= current_user.name %></p>
			<p><%= current_user.location %></p>
			<p><%= current_user.bio %></p>
			<p># of Tweets: <%= current_user.tweets.count %></p>
			<p>Following: <%= current_user.following.length %></p>
			<p>Followers: <%= @follower_count %></p>
		<div>
	</div>
	<div class ="col-md-8">
		<h1>Your Twitter Feed</h1>
		<p>Welcome, <%= link_to show_user_path do %>
			@<%= current_user.username %>!
		<% end %></p>

		<%= render 'tweets/form' %> 
		
		<p>Here's what your friends are saying:</p>

		<div class="row">
			<% @following_tweets.each do |tweet| %>
				<div class="col-md-2">
					<%= image_tag tweet.user.avatar.url(:thumb) %>
				</div>
				<div class="col-md-10">
					<div class="well">
						<p><strong><%= tweet.user.name %></strong> @
						<%= link_to show_user_path(id: tweet.user_id) do %>
			 				<%= tweet.user.username %></p>
			 			<% end %>
			 			<p><%= tweet.message %></p>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/jquery_practice.html.erb
<button id="celebrate">Celebrate</button>

<p class="hiphip"></p>
<p class="hiphip"></p>

<style type="text/css">
	.blue {
		color: blue;
	} 

	.gray {
		color: gray;
	}
</style>



<script>
$(document).ready(function(){
    $("#changestyles").click(function(){
        $("#nowred").css({"color":"red"});
        $("#nowblue").addClass("blue");
        $("#wasgray").removeClass("gray");
    });
});
</script>

<p id="nowred">This text will be red.</p>
<p id="nowblue">This text will be blue.</p>
<p id="wasgray" class="gray">This text was gray.</p>

<button id="changestyles">Change the Styles</button>

<script>
$(document).ready(function(){
    $("#celebrate").hover(function(){
        $(".hiphip").html("HOORAY!");
    });
});
</script>

app/views/epicenter/now_following.html.erb
<h1>Now Following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile &amp Tweets</h1>
<p><%= @user.name %></p>
<p><%= @user.location %></p>
<p><%= @user.bio %></p>

<p>
	<% if current_user.following.include?(@user.id) %>
		

		<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-info", id: "unfollow-btn" %>


	<% else %>
		<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
	<% end %>
</p>

<div class="row">
	<% @user.tweets.each do |tweet| %>
		<div class="col-md-12">
			<div class="well">
			 <p><strong><%= tweet.user.name %></strong> @<%= tweet.user.username %></p>
			 <p><%= tweet.message %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/epicenter/tag_index.html.erb
<h1>All Tags</h1>
<% @tags.each do |tag| %>
<div class="well">
	<h3><%= tag.tag_content %></h3>
	<% tag.tweets.each do |tweet| %>
		<p>@<%= tweet.user.username %> said: <%= tweet.message %></p>
	<% end %>
	</div>
<% end %>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterTalentSouth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<nav id="nav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa fa-home"></i>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
   
        
  	</ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Tags", tag_index_path %></li>
        <li><%= link_to "All Users", all_users_path %></li>
        <li><%= link_to "All Following", all_following_path %></li>
        <li><%= link_to "All Followers", all_followers_path %></li>
        <li class="mtop">
        
        <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Welcome, <%= current_user.username %>!
        <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </li>


        <li>
          <%= link_to new_tweet_path do %>
          <i class="fa fa-pencil-square-o"></i>
          <% end %>
        </li>
        <li></li>
        <li class="dropdown">
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% end %>


<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :message %>
  </div>
  <div class="field-group cant-see-me">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit "Tweet!", class: "btn btn-primary" %>
  </div>
</p>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  @<%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>